import Handlebars from 'handlebars';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { GardenerConfig } from '../config/index.js';

// ---------------------------------------------------------------------------
// Embedded Handlebars templates
// These are the source-of-truth templates that get rendered to .gardener/prompts/
// at runtime. The .hbs files in src/prompts/templates/ are kept for reference
// but the dist bundle uses these embedded strings.
// ---------------------------------------------------------------------------

const TEMPLATES: Record<string, string> = {
  context: `# Vault Context (Auto-Generated)

> This file is auto-generated by vault-gardener from \`.gardener/config.yaml\`.
> Do not edit manually — run \`vault-gardener config regen\` to regenerate.

## Vault Structure

{{#each folders}}
{{@key}}: \`{{this}}/\`
{{/each}}

## Routing Rules

### Step 1: Classify — episodic or entity?
- **Episodic** (first-person, temporal markers, meetings, decisions) → \`{{folders.journal}}/\` via Binder
- **Entity/Reference** (resources, people, orgs, clips) → direct to folder below

### Step 2: Route entity/reference items:
- Uncertain where it goes? → \`{{folders.inbox}}/\`
{{#if folders.projects}}- Has a deadline or deliverable? → \`{{folders.projects}}/\`{{/if}}
{{#if folders.roles}}- Ongoing role or responsibility? → \`{{folders.roles}}/\`{{/if}}
{{#if folders.resources}}- Reference/knowledge to retrieve later? → \`{{folders.resources}}/{topic-subfolder}/\`{{/if}}
{{#if folders.people}}- About a person? → \`{{folders.people}}/\`{{/if}}
{{#if folders.orgs}}- About an organization? → \`{{folders.orgs}}/\`{{/if}}
{{#if folders.playbooks}}- Repeatable process or SOP? → \`{{folders.playbooks}}/\`{{/if}}
{{#if folders.sources}}- External article, book, paper? → \`{{folders.sources}}/\`{{/if}}
{{#if folders.mocs}}- Index/hub note? → \`{{folders.mocs}}/\`{{/if}}
{{#if folders.archive}}- Done or no longer relevant? → \`{{folders.archive}}/\`{{/if}}

## Topic Taxonomy

{{#each topics}}
### {{@key}}
Keywords: {{#each this}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

## Frontmatter Standards

### Required Fields (all notes)
{{#each frontmatter.required}}
- \`{{this}}\`
{{/each}}

### Status Values
{{#each frontmatter.statuses}}
- \`{{this}}\`
{{/each}}

### Type Values
{{#each frontmatter.types}}
- \`{{this}}\`
{{/each}}

## Note Lifecycle

\`\`\`
seed → growing → evergreen → archived       (all notes)
seed → consolidated                          (event journals, after Store items processed)
\`\`\`

| Status | Gardener behavior |
|--------|-------------------|
| **seed** | Maximum attention. Enriches content, fills frontmatter, adds links, organizes. |
| **growing** | Active management. Adds links, updates beliefs, tracks goals. |
| **evergreen** | Passive. Only adds back-links. Does NOT modify content. |
| **archived** | Ignored. Gardener skips entirely. |
| **consolidated** | Event journals only. All Store items processed. Gardener skips. |

### What the gardener NEVER does:
- Never deletes any note
- Never auto-archives (only suggests)
- Never demotes status
- Never modifies evergreen content (only adds back-links in See Also)

## File Naming

| Type | Pattern | Example |
|------|---------|---------|
| People | \`Firstname Lastname.md\` | \`Jane Smith.md\` |
| Organizations | \`Name.md\` | \`Acme Corp.md\` |
| Resources/Topics | \`Title Case.md\` | \`Machine Learning Basics.md\` |
| Projects | \`Project - Name.md\` | \`Project - Website Redesign.md\` |
| Daily journals | \`YYYY-MM-DD.md\` | \`2026-01-19.md\` |
| Event journals | \`YYYY-MM-DD Kind - Title.md\` | \`2026-01-19 Insight - API Design.md\` |
| Meeting notes | \`YYYY-MM-DD Meeting - Topic.md\` | \`2026-01-19 Meeting - Sprint Review.md\` |

## Formatting Conventions

- Tags: kebab-case (\`#machine-learning\`)
- Links: Always \`[[WikiLinks]]\`
- Max 5 tags per note
- Lead with key insight (inverted pyramid)

## Batch Limits

{{#each limits}}
- {{@key}}: {{this}}
{{/each}}

## Protected Paths (NEVER touch)

{{#each protected}}
- \`{{this}}/\`
{{/each}}

## Concurrency Safety

Before modifying any file, check its modification time. If the file was
modified in the last 5 minutes, SKIP it — the user may be actively editing.`,

  // ---------------------------------------------------------------------------
  garden: `# Gardener — AI-Powered Vault Maintenance Pipeline

Run the full vault gardener. Three phases execute in sequence:
1. **Seed** — process inbox into journals and semantic folders
2. **Nurture** — repair structure, consolidate knowledge, build links
3. **Tend** — lifecycle management, organization, enrichment

**No information is ever deleted** — only reorganized, enriched, and connected.

## Protected Paths

**NEVER read, modify, or process files in these locations:**
{{#each protected}}
- \`{{this}}/\`
{{/each}}

## Concurrency Safety

Before modifying any file, check its modification time. If the file was
modified in the last 5 minutes, SKIP it — the user may be actively editing.
Log skipped files with reason "skipped: recently modified".

## Instructions

First, read \`.gardener/context.md\` to understand vault structure and rules.

Then execute the pipeline:

### Phase 1: Seed
Read \`.gardener/prompts/seed.md\` and execute all steps.

### Phase 2: Nurture
Read \`.gardener/prompts/nurture.md\` and execute all steps.

### Phase 3: Tend
Read \`.gardener/prompts/tend.md\` and execute all steps.

## Output

Combined summary from all three phases:
- **Seed**: Inbox items triaged, journals created, salience tags applied, items routed
- **Nurture**: Structure repaired, beliefs consolidated, playbooks/MOCs generated, links added
- **Tend**: Stale notes reviewed, resources organized, notes enriched`,

  // ---------------------------------------------------------------------------
  seed: `# Seed — Intake & Routing

Process inbox items into journals and semantic folders. Raw captures become
structured episodic and semantic memories.

**No information is ever deleted** — only reorganized, enriched, and connected.

## Safety

- **Never delete** — only reorganize, enrich, connect
- **Skip recently modified** — if file modified in last 5 min, skip it
- **Never touch protected paths**: {{#each protected}}\`{{this}}/\` {{/each}}

## Instructions

Read \`.gardener/context.md\` for vault structure and routing rules.

---

## Step 0 — Document Cleanup

Run cleanup on recently modified notes before other maintenance:

1. **Find recent notes**: Identify all notes modified in the last 7 days
   (skip protected paths)

2. **Skip already clean**: Exclude notes with \`status: evergreen\`

3. **Run cleanup phases** for each note:
   - **Format**: Normalize whitespace, bullets, headings, dates
   - **Structure**: Add missing sections for document type
   - **Enrich**: Fill thin content (<100 words) with context
   - **Cross-link**: Discover and add WikiLinks to related notes

4. **Processing rules**:
   - Skip protected paths
   - Never reduce content, only add or restructure
   - Preserve code blocks, WikiLinks, and embeds exactly

---

## Step 1 — Triage

Classify each \`{{folders.inbox}}/\` item:

**EPISODIC signals** (any match → episodic):
- First-person pronouns: "I", "my", "we", "our"
- Temporal markers: "today", "yesterday", "just now", "this morning"
- Frontmatter: \`type: meeting\`, \`type: journal\`
- Contains \`[decision]\`, \`[milestone]\`, \`[insight]\`, \`[met]\` tags
- Voice memo transcription

**ENTITY/REFERENCE signals** (any match → direct route):
- Frontmatter: \`type: resource\`, \`person\`, \`org\`
- Contains URL as primary content
- Filename matches person/org naming patterns
- Is a clipped article (\`type: clip\`, \`source: url\`)

**AMBIGUOUS** → default episodic

- Episodic items → **Step 1.1 (Binder)**
- Entity/reference items → **Step 1.3 (Route Remaining)**

## Step 1.1 — Binder

Process episodic inbox items into journals.

**Content maturity check:**
- Structured (headings, links, checklists, or >50 words) → process now
- Bare capture (<50 words, no structure) → skip if < 12h old
- Has explicit routing tag → process immediately

### SMALL captures (< 50 words, single thought)

1. Find or create \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.daily}}/YYYY-MM-DD.md\`
2. Append under \`## Captures\`:
   \`\`\`
   - {content} — [[source-if-any]] ({HH:MM})
   \`\`\`
3. Delete inbox file

### LARGE captures (>= 50 words, OR has headings, OR contains [decision]/[milestone]/[insight])

1. **Determine Kind** from content:
   | Signal | Kind |
   |--------|------|
   | "decided", "chose", "going with" | Decision |
   | "realized", "learned", "turns out" | Insight |
   | "shipped", "launched", "completed" | Milestone |
   | "failed", "broke", "mistake" | Failure |
   | "met", "talked", "called" | Encounter |
   | "won", "closed", "landed" | Win |
   | Default | Observation |

2. **Create event journal**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.daily}}/YYYY-MM-DD {Kind} - {Title}.md\`
3. **Apply frontmatter**:
   \`\`\`yaml
   ---
   created: YYYY-MM-DD
   updated: YYYY-MM-DD
   tags: [journal, {kind-lowercase}]
   status: seed
   type: journal
   kind: {Kind}
   ---
   \`\`\`
   Sections: \`## Context\`, \`## Takeaways\`, \`## Store\`

4. **Link from daily note** under \`## Events\`
5. Delete inbox file

## Step 1.2 — Salience Tagger

Scan journals modified in last 24h.

**HIGH salience** → add \`#salient\`:
- Explicit tags: \`#salient\`, \`#urgent\`, \`#painful\`, \`#win\`
- Risk language: "risk", "threat", "red flag", "critical"
- Emotional markers: "surprised", "shocked", "changed my mind"
- High stakes: "$", "million", "funding", "fired", "hired"

**MEDIUM salience** → add \`#notable\`:
- "interesting", "worth noting", "keep in mind", "opportunity"

**Idempotent:** skip if already tagged.

## Step 1.3 — Route Remaining Inbox

Route entity/reference items to folders:

{{#if folders.people}}- **People** → \`{{folders.people}}/\`{{/if}}
{{#if folders.orgs}}- **Orgs** → \`{{folders.orgs}}/\`{{/if}}
{{#if folders.projects}}- **Projects** → \`{{folders.projects}}/\`{{/if}}
{{#if folders.sources}}- **Sources** (articles, books, clips) → \`{{folders.sources}}/\`{{/if}}
{{#if folders.resources}}- **Concepts/Knowledge** → \`{{folders.resources}}/{topic-subfolder}/\`{{/if}}
{{#if folders.playbooks}}- **Playbooks** (how-tos, processes) → \`{{folders.playbooks}}/\`{{/if}}

For each routed item:
- Enrich with proper frontmatter
- Add relevant links to existing notes
- Move to destination

## Step 1.4 — People Auto-Research

Detect sparse people notes and enrich:

1. Find sparse people notes in \`{{folders.people}}/\`:
   - File size < 500 bytes, \`status: seed\`, NOT \`auto-researched: true\`
   - NOT modified within last 7 days
2. Batch limit: 3-5 notes per run
3. Web search for job title, company, brief bio
4. Update with attribution banner
5. Safety: only fill empty sections, never overwrite

---

## Commit (if git available)

\`\`\`bash
git add -A && git commit -m "vault-gardener seed: {date} ({count} items processed)"
\`\`\`

---

## Output

Summary:
- **Cleanup**: {files} files cleaned
- **Triage**: {episodic} episodic, {entity} entity items classified
- **Journals**: {daily} daily captures, {event} event journals created
- **Salience**: {high} high, {medium} medium tags applied
- **Routing**: {routed} items routed to folders
- **People**: {researched} people notes auto-researched`,

  // ---------------------------------------------------------------------------
  nurture: `# Nurture — Structure & Knowledge Building

Repair structure, consolidate episodic memories into semantic knowledge, and build
the knowledge graph. Structural integrity first, then belief updates, playbook
extraction, MOC generation, and semantic linking.

**No information is ever deleted** — only reorganized, enriched, and connected.

## Safety

- **Never delete** — only reorganize, enrich, connect
- **Skip recently modified** — if file modified in last 5 min, skip it
- **Never touch protected paths**: {{#each protected}}\`{{this}}/\` {{/each}}

## Instructions

Read \`.gardener/context.md\` for vault structure and rules.

---

## Step 1 — Structural Integrity Checks

- **Root orphans**: Find \`.md\` files in vault root (not in any folder). Move to \`{{folders.inbox}}/\` for triage.
- **Depth check**: Flag folders nested deeper than 3 levels.
- **Duplicate detection**: Find notes with identical titles in different folders. Log for review.
- **Broken WikiLinks**: Scan for \`[[links]]\` pointing to non-existent notes. Auto-fix close matches (case-insensitive). Log rest.
- **Empty notes**: Find notes with only frontmatter and no body content, older than 7 days. Flag for review.

## Step 1.1 — Frontmatter Compliance Sweep

Scan notes modified in the last 14 days. Verify required frontmatter:

- **All notes**: {{#each frontmatter.required}}\`{{this}}\`{{#unless @last}}, {{/unless}}{{/each}}
{{#if folders.projects}}- **Projects**: \`deadline\`, \`outcome\`, \`priority\`, \`role\`{{/if}}
{{#if folders.roles}}- **Roles**: \`role\`, \`cadence\`{{/if}}
{{#if folders.people}}- **People**: \`relationship\`, \`company\`, \`last-contact\`{{/if}}
{{#if folders.orgs}}- **Orgs**: \`org-type\`, \`industry\`, \`website\`, \`relationship\`{{/if}}
{{#if folders.resources}}- **Resources**: \`source\`, \`author\`, \`rating\`, \`topic\`{{/if}}

Fill missing fields with sensible defaults:
- \`created\`/\`updated\` → file dates
- \`status\` → \`seed\` if new
- \`type\` → infer from folder location
- \`tags\` → infer 1-3 from title/content

## Step 1.2 — Orphan Triage

Identify notes with no incoming links (orphans).

- \`status: seed\` + >14 days + 0 incoming links → add review comment, try to auto-link
- \`status: growing\` + orphan → add to "Needs Attention" list
- \`status: evergreen\` + orphan → attempt auto-link

**Never auto-archive orphans.**

---

## Step 2 — Consolidator

Scan all journals with \`## Store\` sections.

### Process checked items (\`- [x] Update [[Target]] with {content}\`)

1. Open target note
2. Find or create \`## Beliefs (with receipts)\` section
3. Count supporting journals:
   - 2+ journals → \`✅ confirmed\`
   - 1 journal → \`🟡 emerging\`
   - Explicitly hypothesis → \`🧪 hypothesis\`
4. Append bullet: \`- {marker} {belief} — evidence: [[Journal 1]], [[Journal 2]]\`
5. **Contradiction check:** If conflicting belief found, mark both \`🟡 emerging\` and add warning callout
6. Mark Store checkbox as consolidated

**Never delete beliefs.** Mark \`⛔ retracted\` when outdated.

**Batch limit:** Max {{limits.beliefs_per_run}} belief updates per run.

## Step 2.1 — Playbook Builder

Detect procedural patterns across journals.

**Triggers:**
- 3+ journals share 2+ tags AND contain step-lists
- OR note tagged \`#playbook-candidate\`

**Actions:**
- Create/update \`{{folders.playbooks}}/{topic-slug}.md\`
- Sections: \`## Trigger\`, \`## Steps\`, \`## Failure Modes\`, \`## Evidence\`

**Batch limit:** Max {{limits.playbooks_per_run}} playbooks per run.

## Step 2.2 — Auto-MOC

Generate Maps of Content for frequently-mentioned entities.

**Threshold (adaptive):**
| Vault Notes | Base | Salient Override |
|-------------|------|------------------|
| < 100 | 5 | 3 |
| 100-500 | 8 | 5 |
| 500+ | 12 | 7 |

**Actions:**
- Create \`{{folders.mocs}}/MOC - {Entity}.md\`
- Sections: \`## Timeline\`, \`## Key Beliefs\`, \`## Related\`, \`## Open Questions\`

**Batch limit:** Max {{limits.mocs_per_run}} new MOCs per run.

---

## Step 3 — Semantic Similarity Linking

Analyze notes modified in the last 14 days. Find related notes using:
- **Tag overlap**: 2+ topic-specific tags shared (exclude structural tags)
- **Title word overlap**: Significant shared words
- **Topic match**: Same \`topic\` frontmatter
- **Content keywords**: Top 5 keywords, find notes mentioning them

For each candidate pair with no existing link:
- Add bidirectional WikiLinks in \`## See Also\` section

**Limit:** Max {{limits.links_per_run}} new links per run.

---

## Commit (if git available)

\`\`\`bash
git add -A && git commit -m "vault-gardener nurture: {date} ({beliefs} beliefs, {links} links)"
\`\`\`

---

## Output

Summary:
- **Structure**: {root} orphans moved, {dupes} duplicates found, {broken} links fixed
- **Frontmatter**: {notes} notes fixed, {fields} fields added
- **Orphans**: {linked} auto-linked, {flagged} flagged
- **Beliefs**: {consolidated} beliefs consolidated, {contradictions} contradictions
- **Playbooks**: {created} created, {updated} updated
- **MOCs**: {created} new MOCs, {updated} refreshed
- **Links**: {count} new links, {cross} cross-domain connections`,

  // ---------------------------------------------------------------------------
  tend: `# Tend — Lifecycle & Enrichment

Review note lifecycle, organize semantic memory into topic folders, and progressively
enrich sparse notes. Pruning, organizing, and nurturing the knowledge garden.

**No information is ever deleted** — only reorganized, enriched, and connected.

## Safety

- **Never delete** — only reorganize, enrich, connect
- **Skip recently modified** — if file modified in last 5 min, skip it
- **Never touch protected paths**: {{#each protected}}\`{{this}}/\` {{/each}}

## Instructions

Read \`.gardener/context.md\` for vault structure and rules.

---

## Step 1 — Stale Note Review

Non-destructive review. **Never auto-archive or delete.**

| Condition | Action |
|-----------|--------|
| \`seed\` + 0 incoming links + >14 days old | Add review comment. Find 2-3 related notes and add WikiLinks. |
| \`seed\` + >30 days old | Flag in summary: "Needs attention — develop or connect." |
| Event journal with all Store items processed | Set \`status: consolidated\`. |

## Step 1.1 — Semantic Memory Organizer

Auto-organize \`{{folders.resources}}/\` into topic subfolders.

1. **Scan loose files** in \`{{folders.resources}}/\` root
2. **Detect topic** from title, tags, content, \`topic\` frontmatter
3. **Route to matching subfolder:**
   - Subfolder exists → move file, update \`topic\` frontmatter
   - No subfolder but {{auto_grow.resources}}+ loose files share topic → create subfolder + index note
   - Topic unclear or < {{auto_grow.resources}} matches → leave in root
4. **Update index notes** with file links
5. **Never move files OUT of existing subfolders**

**Topic taxonomy:**
{{#each topics}}
- **{{@key}}**: {{#each this}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

New topic categories auto-created when {{auto_grow.resources}}+ notes share keywords not covered above.

**Batch limit:** Max {{limits.organize_per_run}} files organized per run.

---

## Step 2 — Journal Generation

Generate higher-level journal summaries when threshold data exists.

### Weekly Summary
- **Trigger**: 3+ daily entries exist for the week
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.weekly}}/YYYY-WNN.md\`
- **Style**: {{journal.style.weekly}}
- **Sections**: Highlights, Decisions, Learnings, People, Open Items for Next Week
- **Links**: Back-links to each daily + event journal

### Monthly Summary
- **Trigger**: 2+ weekly entries exist for the month
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.monthly}}/YYYY-MM.md\`
- **Style**: {{journal.style.monthly}}
- **Sections**: Highlights, Goal Progress, Key Relationships, Knowledge Growth, Gardener Recommendations

### Quarterly Reflection
- **Trigger**: 2+ monthly entries exist for the quarter
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.quarterly}}/YYYY-QN.md\`
- **Style**: {{journal.style.quarterly}}
- **Sections**: Quarter in Review, Progress Against Themes, Goal Assessment, Key Learnings, Top Relationships, Gardener Recommendations

### Yearly Review
- **Trigger**: User sets themes in yearly note
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.yearly}}/YYYY.md\`
- **Style**: {{journal.style.yearly}}
- **Sections**: Themes, Goals & Plans, Progress Tracker, Key Events, Key Learnings, Gardener Recommendations
- **Lifecycle**: Created on Jan 1st (or init). Updated monthly. Comprehensive Q4 review.

---

## Step 3 — Progressive Enrichment Queue

Process sparse notes for enrichment:

1. Scan vault for candidates:
   - Notes with \`status: seed\` and content < 200 words
   - Notes with 0 outgoing WikiLinks
   - Resource notes missing \`## Key Takeaways\`
2. **Priority**: Notes referenced by more journals get enriched first
3. Process top {{limits.enrich_per_run}} items:
   - Extract key concepts and create/link resource notes
   - Add 3-5 WikiLinks to related notes
   - Expand thin sections
   - Promote \`seed\` → \`growing\` if substantially enriched
4. Report: "Enriched {count} notes, {remaining} remaining in queue"

---

## Commit (if git available)

\`\`\`bash
git add -A && git commit -m "vault-gardener tend: {date} ({enriched} enriched, {organized} organized)"
\`\`\`

---

## Output

Summary:
- **Stale review**: {flagged} notes flagged, {consolidated} journals consolidated
- **Organization**: {organized} files organized into topic subfolders
- **Journals**: {weekly} weekly, {monthly} monthly, {quarterly} quarterly generated
- **Enrichment**: {enriched} notes enriched, {remaining} remaining in queue`,
};

// ---------------------------------------------------------------------------
// Template accessor
// ---------------------------------------------------------------------------

function getTemplate(name: string): string {
  const template = TEMPLATES[name];
  if (!template) {
    const available = Object.keys(TEMPLATES).join(', ');
    throw new Error(`Unknown template "${name}". Available: ${available}`);
  }
  return template;
}

// ---------------------------------------------------------------------------
// Compile cache — avoid recompiling the same template on repeated calls
// ---------------------------------------------------------------------------

const compiled = new Map<string, HandlebarsTemplateDelegate>();

function compile(name: string): HandlebarsTemplateDelegate {
  let fn = compiled.get(name);
  if (!fn) {
    fn = Handlebars.compile(getTemplate(name), { noEscape: true });
    compiled.set(name, fn);
  }
  return fn;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Phase prompt names (written to .gardener/prompts/{name}.md) */
const PHASE_NAMES = ['garden', 'seed', 'nurture', 'tend'] as const;

/**
 * Render phase prompts (garden, seed, nurture, tend) to `{gardenerDir}/prompts/`.
 */
export async function renderPrompts(
  gardenerDir: string,
  config: GardenerConfig,
): Promise<void> {
  const promptsDir = join(gardenerDir, 'prompts');
  await mkdir(promptsDir, { recursive: true });

  await Promise.all(
    PHASE_NAMES.map(async (name) => {
      const render = compile(name);
      const output = render(config);
      await writeFile(join(promptsDir, `${name}.md`), output, 'utf-8');
    }),
  );
}

/**
 * Render the context file to `{gardenerDir}/context.md`.
 */
export async function renderContext(
  gardenerDir: string,
  config: GardenerConfig,
): Promise<void> {
  await mkdir(gardenerDir, { recursive: true });

  const render = compile('context');
  const output = render(config);
  await writeFile(join(gardenerDir, 'context.md'), output, 'utf-8');
}

/**
 * Render all templates: context + phase prompts.
 */
export async function renderAll(
  gardenerDir: string,
  config: GardenerConfig,
): Promise<void> {
  await Promise.all([
    renderContext(gardenerDir, config),
    renderPrompts(gardenerDir, config),
  ]);
}
