import Handlebars from 'handlebars';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { GardenerConfig } from '../config/index.js';

// ---------------------------------------------------------------------------
// Handlebars helpers
// ---------------------------------------------------------------------------

Handlebars.registerHelper('eq', (a: unknown, b: unknown) => a === b);

// ---------------------------------------------------------------------------
// Embedded Handlebars templates
// These are the source-of-truth templates that get rendered to .gardener/prompts/
// at runtime. The .hbs files in src/prompts/templates/ are kept for reference
// but the dist bundle uses these embedded strings.
// ---------------------------------------------------------------------------

const TEMPLATES: Record<string, string> = {
  context: `# Vault Context (Auto-Generated)

> This file is auto-generated by vault-gardener from \`.gardener/config.yaml\`.
> Do not edit manually — run \`vault-gardener config regen\` to regenerate.

## Vault Structure

{{#each folders}}
{{@key}}: \`{{this}}/\`
{{/each}}

## Routing Rules

### Step 1: Classify — episodic or entity?
- **Episodic** (first-person, temporal markers, meetings, decisions) → \`{{folders.journal}}/\` via Binder
- **Entity/Reference** (resources, people, orgs, clips) → direct to folder below

### Step 2: Route entity/reference items:
- Uncertain where it goes? → \`{{folders.inbox}}/\`
{{#if folders.projects}}- Has a deadline or deliverable? → \`{{folders.projects}}/\`{{/if}}
{{#if folders.roles}}- Ongoing role or responsibility? → \`{{folders.roles}}/\`{{/if}}
{{#if folders.resources}}- Reference/knowledge to retrieve later? → \`{{folders.resources}}/{topic-subfolder}/\`{{/if}}
{{#if folders.people}}- About a person? → \`{{folders.people}}/\`{{/if}}
{{#if folders.orgs}}- About an organization? → \`{{folders.orgs}}/\`{{/if}}
{{#if folders.playbooks}}- Repeatable process or SOP? → \`{{folders.playbooks}}/\`{{/if}}
{{#if folders.sources}}- External article, book, paper? → \`{{folders.sources}}/\`{{/if}}
{{#if folders.mocs}}- Index/hub note? → \`{{folders.mocs}}/\`{{/if}}
{{#if folders.archive}}- Done or no longer relevant? → \`{{folders.archive}}/\`{{/if}}

## Topic Taxonomy

{{#each topics}}
### {{@key}}
Keywords: {{#each this}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

## Frontmatter Standards

### Required Fields (all notes)
{{#each frontmatter.required}}
- \`{{this}}\`
{{/each}}

### Status Values
{{#each frontmatter.statuses}}
- \`{{this}}\`
{{/each}}

### Type Values
{{#each frontmatter.types}}
- \`{{this}}\`
{{/each}}

## Note Lifecycle

\`\`\`
seed → growing → evergreen → archived       (all notes)
seed → consolidated                          (event journals, after Store items processed)
\`\`\`

| Status | Gardener behavior |
|--------|-------------------|
| **seed** | Maximum attention. Enriches content, fills frontmatter, adds links, organizes. |
| **growing** | Active management. Adds links, updates beliefs, tracks goals. |
| **evergreen** | Passive. Only adds back-links. Does NOT modify content. |
| **archived** | Ignored. Gardener skips entirely. |
| **consolidated** | Event journals only. All Store items processed. Gardener skips. |

### What the gardener NEVER does:
- Never deletes any note
- Never auto-archives (only suggests)
- Never demotes status
- Never modifies evergreen content (only adds back-links in See Also)

## File Naming

| Type | Pattern | Example |
|------|---------|---------|
| People | \`Firstname Lastname.md\` | \`Jane Smith.md\` |
| Organizations | \`Name.md\` | \`Acme Corp.md\` |
| Resources/Topics | \`Title Case.md\` | \`Machine Learning Basics.md\` |
| Projects | \`Project - Name.md\` | \`Project - Website Redesign.md\` |
| Daily journals | \`YYYY-MM-DD.md\` | \`2026-01-19.md\` |
| Event journals | \`YYYY-MM-DD Kind - Title.md\` | \`2026-01-19 Insight - API Design.md\` |
| Meeting notes | \`YYYY-MM-DD Meeting - Topic.md\` | \`2026-01-19 Meeting - Sprint Review.md\` |

## Formatting Conventions

- Tags: kebab-case (\`#machine-learning\`)
- Links: Always \`[[WikiLinks]]\`
- Max 5 tags per note
- Lead with key insight (inverted pyramid)

{{#if features.persona}}
## Gardener Persona

**Active persona:** \`{{persona}}\`

| Persona | Behavior |
|---------|----------|
| analytical | Facts and data. Minimal interpretation. Precise and structured. |
| reflective | Questions and deeper meaning. Surfaces connections. Thoughtful commentary. |
| coach | Prescriptive and action-oriented. Recommendations. Pushes for clarity. |

{{/if}}
## Batch Limits

**Base limits** (adjusted by adaptive batch sizing based on vault size):

{{#each limits}}
- {{@key}}: {{this}}
{{/each}}

{{#if features.adaptive_batch_sizing}}
**Adaptive sizing rules:**
- Vault < 100 notes → limits × 2 (small vault, process more aggressively)
- Vault 100-500 notes → standard limits
- Vault 500+ notes → limits ÷ 2 (minimum 3) (large vault, be selective)
{{/if}}

## Memory & Changelog

{{#if features.memory}}- **Memory file**: \`.gardener/memory.md\` — read at start of each phase, updated at end
{{/if}}{{#if features.changelog}}- **Changelog**: \`.gardener/changelog.md\` — appended after each phase (last 50 entries)
{{/if}}

{{#if features.social_content}}
## Social Media Platforms

{{#if social_platforms}}Target platforms: {{#each social_platforms}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}{{/if}}

{{/if}}
## Protected Paths (NEVER touch)

{{#each protected}}
- \`{{this}}/\`
{{/each}}

## Concurrency Safety

Before modifying any file, check its modification time. If the file was
modified in the last 5 minutes, SKIP it — the user may be actively editing.`,

  // ---------------------------------------------------------------------------
  garden: `# Gardener — AI-Powered Vault Maintenance Pipeline

Run the full vault gardener. Three phases execute in sequence:
1. **Seed** — process inbox into journals and semantic folders
2. **Nurture** — repair structure, synthesize knowledge, build links
3. **Tend** — lifecycle management, organization, enrichment

**No information is ever deleted** — only reorganized, enriched, and connected.

{{#if features.persona}}
## Persona

{{#if (eq persona "analytical")}}You are an **analytical** gardener. Focus on facts, data, and minimal interpretation. Be precise, structured, and evidence-based. Avoid speculation.{{/if}}
{{#if (eq persona "reflective")}}You are a **reflective** gardener. Ask questions, explore deeper meaning, and surface connections. Balance structure with thoughtful commentary.{{/if}}
{{#if (eq persona "coach")}}You are a **coaching** gardener. Be prescriptive and action-oriented. Frame observations as recommendations. Push for clarity and commitment.{{/if}}

{{/if}}
{{#if features.memory}}
## Memory

Read \`.gardener/memory.md\` if it exists. This file contains context from previous runs:
- What was done, what was deferred, running vault observations
- Use this to avoid re-processing and to continue multi-run projects
- Each phase will update memory with its results

{{/if}}
## Protected Paths

**NEVER read, modify, or process files in these locations:**
{{#each protected}}
- \`{{this}}/\`
{{/each}}

## Concurrency Safety

Before modifying any file, check its modification time. If the file was
modified in the last 5 minutes, SKIP it — the user may be actively editing.
Log skipped files with reason "skipped: recently modified".

## Instructions

First, read \`.gardener/context.md\` to understand vault structure and rules.

Then execute the pipeline:

### Phase 1: Seed
Read \`.gardener/prompts/seed.md\` and execute all steps.

### Phase 2: Nurture
Read \`.gardener/prompts/nurture.md\` and execute all steps.

### Phase 3: Tend
Read \`.gardener/prompts/tend.md\` and execute all steps.

## Run Report

Each phase template includes instructions to write \`.gardener/run-report.json\`.
The **seed** phase creates the file. **Nurture** and **tend** read the existing file
and append their phase to the \`phases\` array. The final file contains all three phases.

## Output

Combined summary from all three phases:
- **Seed**: Inbox items triaged, journals created, salience tags applied, items routed, questions extracted, commitments tracked
- **Nurture**: Structure repaired, beliefs synthesized, playbooks/MOCs generated, entity + semantic + transitive links added, tags normalized, knowledge gaps identified, co-mention networks updated
- **Tend**: Stale notes reviewed, resources organized, notes enriched with context anchoring and summaries, journals generated with themes/attention/goals/social content`,

  // ---------------------------------------------------------------------------
  seed: `# Seed — Intake & Routing

Process inbox items into journals and semantic folders. Raw captures become
structured episodic and semantic memories.

**No information is ever deleted** — only reorganized, enriched, and connected.

{{#if features.persona}}
## Persona

{{#if (eq persona "analytical")}}You are an **analytical** gardener. Focus on facts, data, and minimal interpretation. Be precise, structured, and evidence-based. Avoid speculation.{{/if}}
{{#if (eq persona "reflective")}}You are a **reflective** gardener. Ask questions, explore deeper meaning, and surface connections. Balance structure with thoughtful commentary.{{/if}}
{{#if (eq persona "coach")}}You are a **coaching** gardener. Be prescriptive and action-oriented. Frame observations as recommendations. Push for clarity and commitment.{{/if}}

{{/if}}
{{#if features.memory}}
## Memory

Read \`.gardener/memory.md\` if it exists. This file contains context from previous runs —
what was done, what was deferred, running observations about vault state. Use this to:
- Avoid re-processing items handled in previous runs
- Continue multi-run projects from where they left off
- Make strategic decisions about what to prioritize this run

{{/if}}
## Safety

- **Never delete** — only reorganize, enrich, connect
- **Skip recently modified** — if file modified in last 5 min, skip it
- **Never touch protected paths**: {{#each protected}}\`{{this}}/\` {{/each}}

## Instructions

Read \`.gardener/context.md\` for vault structure and routing rules.

---

## Step 0 — Document Cleanup

Run cleanup on recently modified notes before other maintenance:

1. **Find recent notes**: Identify all notes modified in the last 7 days
   (skip protected paths)

2. **Skip already clean**: Exclude notes with \`status: evergreen\`

3. **Run cleanup phases** for each note:
   - **Format**: Normalize whitespace, bullets, headings, dates
   - **Structure**: Add missing sections for document type
   - **Enrich**: Fill thin content (<100 words) with context
   - **Cross-link**: Discover and add WikiLinks to related notes

4. **Processing rules**:
   - Skip protected paths
   - Never reduce content, only add or restructure
   - Preserve code blocks, WikiLinks, and embeds exactly

---

## Step 1 — Triage

Classify each \`{{folders.inbox}}/\` item:

**EPISODIC signals** (any match → episodic):
- First-person pronouns: "I", "my", "we", "our"
- Temporal markers: "today", "yesterday", "just now", "this morning"
- Frontmatter: \`type: meeting\`, \`type: journal\`
- Contains \`[decision]\`, \`[milestone]\`, \`[insight]\`, \`[met]\` tags
- Voice memo transcription

**ENTITY/REFERENCE signals** (any match → direct route):
- Frontmatter: \`type: resource\`, \`person\`, \`org\`
- Contains URL as primary content
- Filename matches person/org naming patterns
- Is a clipped article (\`type: clip\`, \`source: url\`)

**AMBIGUOUS** → default episodic

- Episodic items → **Step 1.1 (Binder)**
- Entity/reference items → **Step 1.3 (Route Remaining)**

## Step 1.1 — Binder

Process episodic inbox items into journals.

**Content maturity check:**
- Structured (headings, links, checklists, or >50 words) → process now
- Bare capture (<50 words, no structure) → skip if < 12h old
- Has explicit routing tag → process immediately

### SMALL captures (< 50 words, single thought)

1. Find or create \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.daily}}/YYYY-MM-DD.md\`
2. Append under \`## Captures\`:
   \`\`\`
   - {content} — [[source-if-any]] ({HH:MM})
   \`\`\`
3. Delete inbox file

{{#if features.this_time_last_year}}
### This Time Last Year (#29)

When creating or updating a daily journal, look for journals from roughly one year ago.
Search \`{{folders.journal}}/{YYYY-1}/{{journal.journal_subfolders.daily}}/\` for any daily
or event journals within ±3 days of today's date last year (7-day window).

**Search order** (pick the best single match):
1. Exact date last year (\`{YYYY-1}-MM-DD\`)
2. Same weekday in the nearest week (e.g., if today is Tuesday, find last year's nearest Tuesday)
3. Any journal within the ±3 day window, preferring the one with the most content

If found, add a callout at the top of the daily note (after frontmatter):

\`\`\`markdown
> [!calendar] This Time Last Year
> {2-3 sentence summary of that day's journal}
> — [[{matched-date}]]
\`\`\`

If multiple journals exist in the window (e.g., a daily + event journals), summarize the
most interesting one and link to the others:

\`\`\`markdown
> [!calendar] This Time Last Year
> {2-3 sentence summary of the most notable entry}
> — [[{matched-date}]] · also: [[{YYYY-1}-MM-DD Kind - Title]]
\`\`\`

Only add once per daily note. Skip if a \`[!calendar] This Time Last Year\` callout already exists.

{{/if}}
### LARGE captures (>= 50 words, OR has headings, OR contains [decision]/[milestone]/[insight])

1. **Determine Kind** from content:
   | Signal | Kind |
   |--------|------|
   | "decided", "chose", "going with" | Decision |
   | "realized", "learned", "turns out" | Insight |
   | "shipped", "launched", "completed" | Milestone |
   | "failed", "broke", "mistake" | Failure |
   | "met", "talked", "called" | Encounter |
   | "won", "closed", "landed" | Win |
   | Default | Observation |

2. **Create event journal**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.daily}}/YYYY-MM-DD {Kind} - {Title}.md\`
3. **Apply frontmatter**:
   \`\`\`yaml
   ---
   created: YYYY-MM-DD
   updated: YYYY-MM-DD
   tags: [journal, {kind-lowercase}]
   status: seed
   type: journal
   kind: {Kind}
   ---
   \`\`\`
   Sections: \`## Context\`, \`## Takeaways\`, \`## Store\`

{{#if features.meeting_enhancement}}
4. **Kind-specific enhancements:**

   **Encounter (type: meeting):**
   - Add \`## Action Items\` with checkboxes: \`- [ ] {action} — @{owner} (due: {date})\`
   - Add \`## Key Quotes\` attributed to attendees
   - Add \`## Follow-up Required\` with timeline
   - Link to relevant \`{{folders.people}}/\` and \`{{folders.orgs}}/\` notes
   - Update \`last-contact\` frontmatter on referenced person notes

{{/if}}
{{#if features.question_tracker}}
5. **Extract questions** (#3 Question Tracker):
   Scan journal content for substantive questions — "I wonder...", "need to figure out...",
   sentences ending in \`?\` about decisions, strategy, or understanding.
   **Filter:** Only track questions about decisions, strategy, understanding, or personal growth.
   Ignore logistics, scheduling, and rhetorical questions.
   Collect into \`## Open Questions\` section on the event journal.
   Also append to the relevant MOC's \`## Open Questions\` section if a MOC exists for the topic.

{{/if}}
{{#if features.commitment_tracker}}
6. **Extract commitments** (#24 Commitment Tracker):
   Scan for commitments to people — "I told {person} I'd...", "promised to...",
   "need to send {person}...", "agreed to..." with deadlines if mentioned.
   Add to \`## Commitments\` section on the relevant person note in \`{{folders.people}}/\`:
   \`\`\`markdown
   - [ ] {commitment} — from [[{journal-date}]] (due: {date-if-mentioned})
   \`\`\`
   **Important:** Check the person note's existing commitments and open todo lists in the vault
   to avoid duplicating items already tracked elsewhere.

{{/if}}
7. **Link from daily note** under \`## Events\`
8. Delete inbox file

## Step 1.2 — Salience Tagger

Scan journals modified in last 24h.

**HIGH salience** → add \`#salient\`:
- Explicit tags: \`#salient\`, \`#urgent\`, \`#painful\`, \`#win\`
- Risk language: "risk", "threat", "red flag", "critical"
- Emotional markers: "surprised", "shocked", "changed my mind"
- High stakes: "$", "million", "funding", "fired", "hired"

**MEDIUM salience** → add \`#notable\`:
- "interesting", "worth noting", "keep in mind", "opportunity"

**Idempotent:** skip if already tagged.

## Step 1.3 — Route Remaining Inbox

Route entity/reference items to folders:

{{#if folders.people}}- **People** → \`{{folders.people}}/\`{{/if}}
{{#if folders.orgs}}- **Orgs** → \`{{folders.orgs}}/\`{{/if}}
{{#if folders.projects}}- **Projects** → \`{{folders.projects}}/\`{{/if}}
{{#if folders.sources}}- **Sources** (articles, books, clips) → \`{{folders.sources}}/\`{{/if}}
{{#if folders.resources}}- **Concepts/Knowledge** → \`{{folders.resources}}/{topic-subfolder}/\`{{/if}}
{{#if folders.playbooks}}- **Playbooks** (how-tos, processes) → \`{{folders.playbooks}}/\`{{/if}}

For each routed item:
- Enrich with proper frontmatter
- Add relevant links to existing notes
- Move to destination

## Step 1.4 — People Auto-Research

Detect sparse people notes and enrich:

1. Find sparse people notes in \`{{folders.people}}/\`:
   - File size < 500 bytes, \`status: seed\`, NOT \`auto-researched: true\`
   - NOT modified within last 7 days
2. Batch limit: 3-5 notes per run
3. Web search for job title, company, brief bio
4. Update with attribution banner
5. Safety: only fill empty sections, never overwrite

---

## Commit (if git available)

\`\`\`bash
git add -A && git commit -m "vault-gardener seed: {date} ({count} items processed)"
\`\`\`

---

{{#if features.changelog}}
## Vault Changelog

Append a human-readable summary of this seed run to \`.gardener/changelog.md\`:

\`\`\`markdown
### {YYYY-MM-DD HH:MM} — Seed
- {1-line summary of what was processed}
- Items: {count} triaged, {journals} journals created
- Questions extracted: {count}
- Commitments tracked: {count}
\`\`\`

Keep only the last 50 entries in the changelog file.

{{/if}}
---

{{#if features.memory}}
## Memory Update

Update \`.gardener/memory.md\` with seed phase results. Use YAML frontmatter + markdown:

\`\`\`markdown
---
last_run: {ISO timestamp}
last_phase: seed
items_processed: {count}
items_deferred: {count}
---
## Seed Phase
- Processed {count} inbox items
- {any items deferred and why}
- {observations about vault state relevant to next run}
\`\`\`

Merge with existing memory content — don't overwrite nurture/tend sections.

---

{{/if}}
## Run Report

After completing all steps, write a JSON file to \`.gardener/run-report.json\`:

\\\`\\\`\\\`json
{
  "version": 1,
  "timestamp": "{ISO-8601 timestamp}",
  "phases": [{
    "phase": "seed",
    "started": true,
    "features": [
      { "feature": "{key}", "status": "executed|skipped|error", "counts": { ... }, "reason": "{if skipped/error}" }
    ]
  }],
  "summary": "{1-2 sentence summary of what was done}",
  "warnings": []
}
\\\`\\\`\\\`

Report these features (only report enabled features listed here):
{{#if features.memory}}- \`memory\` — counts: \`{ "read": 0|1, "updated": 0|1 }\`
{{/if}}{{#if features.changelog}}- \`changelog\` — counts: \`{ "entries_written": 0|1 }\`
{{/if}}{{#if features.persona}}- \`persona\` — counts: \`{ "applied": 0|1 }\`
{{/if}}{{#if features.this_time_last_year}}- \`this_time_last_year\` — counts: \`{ "lookbacks_added": {n} }\`
{{/if}}{{#if features.meeting_enhancement}}- \`meeting_enhancement\` — counts: \`{ "meetings_enhanced": {n} }\`
{{/if}}{{#if features.question_tracker}}- \`question_tracker\` — counts: \`{ "questions_extracted": {n} }\`
{{/if}}{{#if features.commitment_tracker}}- \`commitment_tracker\` — counts: \`{ "commitments_tracked": {n} }\`
{{/if}}

Also report core steps as features:
- \`cleanup\` — counts: \`{ "files_cleaned": {n} }\`
- \`triage\` — counts: \`{ "episodic": {n}, "entity": {n} }\`
- \`binder\` — counts: \`{ "daily_captures": {n}, "event_journals": {n} }\`
- \`salience\` — counts: \`{ "high": {n}, "medium": {n} }\`
- \`routing\` — counts: \`{ "items_routed": {n} }\`

**Rules:**
- Report EVERY listed feature, even if skipped (use status "skipped" with a reason)
- The \`phase\` field MUST be exactly one of: \`"seed"\`, \`"nurture"\`, or \`"tend"\` — no other values
- Write valid JSON — no trailing commas, no comments
- If \`.gardener/run-report.json\` already exists (multi-phase run), read it first and APPEND your phase to the \`phases\` array

---

## Output

Summary:
- **Cleanup**: {files} files cleaned
- **Triage**: {episodic} episodic, {entity} entity items classified
- **Journals**: {daily} daily captures, {event} event journals created
- **Salience**: {high} high, {medium} medium tags applied
- **Routing**: {routed} items routed to folders
- **People**: {researched} people notes auto-researched
- **Questions**: {count} substantive questions extracted
- **Commitments**: {count} commitments tracked on person notes`,

  // ---------------------------------------------------------------------------
  nurture: `# Nurture — Structure & Knowledge Building

> **Phase name: nurture** — use exactly \`"nurture"\` in all reporting.

Repair structure, synthesize episodic memories into semantic knowledge, and build
the knowledge graph. Structural integrity first, then belief updates, playbook
extraction, MOC generation, and semantic linking.

**No information is ever deleted** — only reorganized, enriched, and connected.

{{#if features.persona}}
## Persona

{{#if (eq persona "analytical")}}You are an **analytical** gardener. Focus on facts, data, and minimal interpretation. Be precise, structured, and evidence-based. Avoid speculation.{{/if}}
{{#if (eq persona "reflective")}}You are a **reflective** gardener. Ask questions, explore deeper meaning, and surface connections. Balance structure with thoughtful commentary.{{/if}}
{{#if (eq persona "coach")}}You are a **coaching** gardener. Be prescriptive and action-oriented. Frame observations as recommendations. Push for clarity and commitment.{{/if}}

{{/if}}
{{#if features.memory}}
## Memory

Read \`.gardener/memory.md\` if it exists. Use previous run context to:
- Avoid re-processing already-processed beliefs
- Continue linking projects from where they left off
- Prioritize areas flagged in previous runs

{{/if}}
## Safety

- **Never delete** — only reorganize, enrich, connect
- **Skip recently modified** — if file modified in last 5 min, skip it
- **Never touch protected paths**: {{#each protected}}\`{{this}}/\` {{/each}}

## Instructions

Read \`.gardener/context.md\` for vault structure and rules.

---

## Step 1 — Structural Integrity Checks

- **Root orphans**: Find \`.md\` files in vault root (not in any folder). Move to \`{{folders.inbox}}/\` for triage.
- **Depth check**: Flag folders nested deeper than 3 levels.
- **Duplicate detection**: Find notes with identical titles in different folders. Log for review.
- **Broken WikiLinks**: Scan for \`[[links]]\` pointing to non-existent notes. Auto-fix close matches (case-insensitive). Log rest.
- **Empty notes**: Find notes with only frontmatter and no body content, older than 7 days. Flag for review.

## Step 1.1 — Frontmatter Compliance Sweep

Scan notes modified in the last 14 days. Verify required frontmatter:

- **All notes**: {{#each frontmatter.required}}\`{{this}}\`{{#unless @last}}, {{/unless}}{{/each}}
{{#if folders.projects}}- **Projects**: \`deadline\`, \`outcome\`, \`priority\`, \`role\`{{/if}}
{{#if folders.roles}}- **Roles**: \`role\`, \`cadence\`{{/if}}
{{#if folders.people}}- **People**: \`relationship\`, \`company\`, \`last-contact\`{{/if}}
{{#if folders.orgs}}- **Orgs**: \`org-type\`, \`industry\`, \`website\`, \`relationship\`{{/if}}
{{#if folders.resources}}- **Resources**: \`source\`, \`author\`, \`rating\`, \`topic\`{{/if}}

Fill missing fields with sensible defaults:
- \`created\`/\`updated\` → file dates
- \`status\` → \`seed\` if new
- \`type\` → infer from folder location
- \`tags\` → infer 1-3 from title/content

{{#if features.tag_normalization}}
## Step 1.3 — Tag Taxonomy Normalization

Scan tags across recently modified notes. Detect tags that should be merged:

- **Synonyms**: \`#machine-learning\` and \`#ml\`, \`#artificial-intelligence\` and \`#ai\`
- **Plural/singular**: \`#projects\` and \`#project\`
- **Spelling variants**: \`#behaviour\` and \`#behavior\`
- **Hierarchy candidates**: \`#react\` could be under \`#frontend\`

**Actions:**
- Report suggested merges in the run's output — **never auto-merge** (user should confirm)
- If a clear canonical form exists (the one used more often), note it
- Log suggestions to \`## Tag Cleanup\` section in \`.gardener/changelog.md\`

---

{{/if}}
## Step 1.4 — Orphan Triage

Identify notes with no incoming links (orphans).

- \`status: seed\` + >14 days + 0 incoming links → add review comment, try to auto-link
- \`status: growing\` + orphan → add to "Needs Attention" list
- \`status: evergreen\` + orphan → attempt auto-link

**Never auto-archive orphans.**

---

## Step 2 — Belief Synthesizer

Scan all journals with \`## Store\` sections.

### Process checked items (\`- [x] Update [[Target]] with {content}\`)

1. Open target note
2. Find or create \`## Beliefs (with receipts)\` section
3. Count supporting journals:
   - 2+ journals → \`✅ confirmed\`
   - 1 journal → \`🟡 emerging\`
   - Explicitly hypothesis → \`🧪 hypothesis\`
4. Append bullet: \`- {marker} {belief} — evidence: [[Journal 1]], [[Journal 2]]\`
5. **Contradiction check:** If conflicting belief found, mark both \`🟡 emerging\` and add warning callout
6. Mark Store checkbox as processed

**Never delete beliefs.** Mark \`⛔ retracted\` when outdated.
**Remember: this is the NURTURE phase — report as \`"phase": "nurture"\` in run-report.**

**Batch limit:** Max {{limits.beliefs_per_run}} belief updates per run.

{{#if features.co_mention_network}}
## Step 2.0.1 — People Co-Mention Network

For each person note in \`{{folders.people}}/\` modified or referenced in the last 14 days:

1. Scan recent journals for co-mentions — when two people appear in the same journal entry
2. Build or update a \`## Network\` section on the person note:
   \`\`\`markdown
   ## Network
   Frequently mentioned alongside:
   - [[Jane Smith]] (5 entries)
   - [[Acme Corp]] (3 entries)
   - [[Bob Johnson]] (2 entries)
   \`\`\`
3. Only include co-mentions appearing in 2+ journal entries
4. Update counts if section already exists (don't duplicate)

{{/if}}
{{#if features.commitment_tracker}}
## Step 2.0.2 — Commitment Compliance

For each person note in \`{{folders.people}}/\`:
1. Check \`## Commitments\` section for overdue items (past due date)
2. Check open todo lists in the vault to avoid duplicating tracked items
3. Flag overdue commitments in the run summary
4. Cross-reference with recent journals — if a commitment was fulfilled, mark it:
   \`- [x] {commitment} — completed [[{journal-date}]]\`

{{/if}}
---

## Step 2.1 — Playbook Builder

Detect procedural patterns across journals.

**Triggers:**
- 3+ journals share 2+ tags AND contain step-lists
- OR note tagged \`#playbook-candidate\`

**Actions:**
- Create/update \`{{folders.playbooks}}/{topic-slug}.md\`
- Sections: \`## Trigger\`, \`## Steps\`, \`## Failure Modes\`, \`## Evidence\`

**Batch limit:** Max {{limits.playbooks_per_run}} playbooks per run.

## Step 2.2 — Auto-MOC

Generate Maps of Content for frequently-mentioned entities.

**Threshold (adaptive):**
| Vault Notes | Base | Salient Override |
|-------------|------|------------------|
| < 100 | 5 | 3 |
| 100-500 | 8 | 5 |
| 500+ | 12 | 7 |

**Actions:**
- Create \`{{folders.mocs}}/MOC - {Entity}.md\`
- Sections: \`## Timeline\`, \`## Key Beliefs\`, \`## Related\`, \`## Open Questions\`

**Batch limit:** Max {{limits.mocs_per_run}} new MOCs per run.

{{#if features.knowledge_gaps}}
### Knowledge Gap Detection (#19)

During MOC generation/update, identify subtopics that are frequently referenced or implied
but have no dedicated note in the vault:

1. Scan MOC content and linked notes for entity/concept mentions without matching vault notes
2. **Threshold:** Only flag gaps appearing in **5+ journal entries** (not just casual mentions)
3. Add a \`## Knowledge Gaps\` section to the MOC:
   \`\`\`markdown
   ## Knowledge Gaps
   Frequently mentioned but no dedicated note:
   - **transformer architecture** — mentioned in 7 journals, referenced by [[ML Basics]], [[GPT Notes]]
   - **CAP theorem** — mentioned in 5 journals, referenced by [[Distributed Systems]]
   \`\`\`
4. These are natural candidates for future learning or note creation
{{/if}}

---

{{#if features.entity_auto_linking}}
## Step 3 — Entity Mention Auto-Linking

Scan notes modified in the last 14 days for plain-text mentions of known entities
(people, organizations, projects) that exist as vault notes but aren't WikiLinked.

1. Build entity list from filenames in \`{{folders.people}}/\`, \`{{folders.orgs}}/\`, \`{{folders.projects}}/\`
2. For each recently modified note, find plain-text mentions matching entity names (case-insensitive)
3. Convert to WikiLinks: \`I talked to John Smith\` → \`I talked to [[John Smith]]\`
4. **Safety rules:**
   - Only link names that **exactly match** an existing note filename (case-insensitive)
   - Skip names shorter than 4 characters (too many false positives)
   - Don't link inside code blocks, URLs, or existing WikiLinks
   - Use contextual disambiguation: "Apple" the company vs the fruit — only link if context
     matches the note's \`type\` frontmatter
5. **Batch limit:** Max {{limits.links_per_run}} auto-links per run (shared with Step 3.1 below)

{{/if}}
---

## Step 3.1 — Semantic Similarity Linking

Analyze notes modified in the last 14 days. Find related notes using:
- **Tag overlap**: 2+ topic-specific tags shared (exclude structural tags)
- **Title word overlap**: Significant shared words
- **Topic match**: Same \`topic\` frontmatter
- **Content keywords**: Top 5 keywords, find notes mentioning them

For each candidate pair with no existing link:
- Add bidirectional WikiLinks in \`## See Also\` section
{{#if features.backlink_context}}
- **Include context sentence** (#10): Don't add bare links. Include the sentence that
  establishes the connection:
  \`\`\`markdown
  ## See Also
  - [[Thinking in Systems]] — "Applied the systems framework to the architecture decision"
    (from [[Journal 2026-02-15]])
  - [[Conway's Law]] — shares tags #architecture, #org-design
  \`\`\`
  Only add context for **newly-added links** (don't retroactively annotate existing links).
{{/if}}

**Limit:** Max {{limits.links_per_run}} new links per run (shared with Step 3 entity linking).

{{#if features.transitive_links}}
## Step 3.2 — Transitive Link Suggestions

If note A links to B and B links to C, but A does not link to C, and A and C share
tags or keywords, suggest a direct link with the connection path annotated:

\`\`\`markdown
## See Also
- [[Conway's Law]] — transitive via [[Org Design]]: "Your thoughts on hiring connect
  to system design through organizational structure"
\`\`\`

**Scope limit:** Only analyze notes modified in the last 14 days, only 1 hop deep.
Present as suggestions in \`## See Also\` — clearly marked as transitive connections.

{{/if}}
---

## Commit (if git available)

\`\`\`bash
git add -A && git commit -m "vault-gardener nurture: {date} ({beliefs} beliefs, {links} links)"
\`\`\`

---

{{#if features.changelog}}
## Vault Changelog

Append a human-readable summary of this nurture run to \`.gardener/changelog.md\`:

\`\`\`markdown
### {YYYY-MM-DD HH:MM} — Nurture
- {1-line summary of structural work}
- Beliefs: {synthesized} synthesized, {contradictions} contradictions found
- Links: {count} new (entity: {entity}, semantic: {semantic}, transitive: {transitive})
- Tags: {count} merge suggestions
- Knowledge gaps: {count} identified
\`\`\`

Keep only the last 50 entries in the changelog file.

{{/if}}
---

{{#if features.memory}}
## Memory Update

Update \`.gardener/memory.md\` with nurture phase results:

\`\`\`markdown
## Nurture Phase
- Synthesized {count} beliefs, {remaining} Store items remaining
- Added {count} links, {orphans} orphans still unlinked
- Tag merge suggestions: {list}
- {observations for next run}
\`\`\`

Merge with existing memory — preserve seed/tend sections.

---

{{/if}}
## Run Report

After completing all steps, write a JSON file to \`.gardener/run-report.json\`:

\\\`\\\`\\\`json
{
  "version": 1,
  "timestamp": "{ISO-8601 timestamp}",
  "phases": [{
    "phase": "nurture",
    "started": true,
    "features": [
      { "feature": "{key}", "status": "executed|skipped|error", "counts": { ... }, "reason": "{if skipped/error}" }
    ]
  }],
  "summary": "{1-2 sentence summary of what was done}",
  "warnings": []
}
\\\`\\\`\\\`

Report these features (only report enabled features listed here):
{{#if features.memory}}- \`memory\` — counts: \`{ "read": 0|1, "updated": 0|1 }\`
{{/if}}{{#if features.changelog}}- \`changelog\` — counts: \`{ "entries_written": 0|1 }\`
{{/if}}{{#if features.persona}}- \`persona\` — counts: \`{ "applied": 0|1 }\`
{{/if}}{{#if features.tag_normalization}}- \`tag_normalization\` — counts: \`{ "merge_suggestions": {n} }\`
{{/if}}{{#if features.co_mention_network}}- \`co_mention_network\` — counts: \`{ "networks_updated": {n} }\`
{{/if}}{{#if features.knowledge_gaps}}- \`knowledge_gaps\` — counts: \`{ "gaps_identified": {n} }\`
{{/if}}{{#if features.entity_auto_linking}}- \`entity_auto_linking\` — counts: \`{ "mentions_linked": {n} }\`
{{/if}}{{#if features.backlink_context}}- \`backlink_context\` — counts: \`{ "contexts_added": {n} }\`
{{/if}}{{#if features.transitive_links}}- \`transitive_links\` — counts: \`{ "links_suggested": {n} }\`
{{/if}}{{#if features.commitment_tracker}}- \`commitment_tracker\` — counts: \`{ "commitments_reviewed": {n}, "overdue": {n} }\`
{{/if}}

Also report core steps as features:
- \`structural_integrity\` — counts: \`{ "orphans_moved": {n}, "duplicates_found": {n}, "broken_links_fixed": {n} }\`
- \`frontmatter_sweep\` — counts: \`{ "notes_fixed": {n}, "fields_added": {n} }\`
- \`consolidator\` — counts: \`{ "beliefs_consolidated": {n}, "contradictions": {n} }\`
- \`playbook_builder\` — counts: \`{ "created": {n}, "updated": {n} }\`
- \`auto_moc\` — counts: \`{ "created": {n}, "refreshed": {n} }\`
- \`semantic_linking\` — counts: \`{ "links_added": {n} }\`

**Rules:**
- Report EVERY listed feature, even if skipped (use status "skipped" with a reason)
- The \`phase\` field MUST be exactly one of: \`"seed"\`, \`"nurture"\`, or \`"tend"\` — no other values
- Write valid JSON — no trailing commas, no comments
- If \`.gardener/run-report.json\` already exists (multi-phase run), read it first and APPEND your phase to the \`phases\` array

---

## Output

Summary:
- **Structure**: {root} orphans moved, {dupes} duplicates found, {broken} links fixed
- **Frontmatter**: {notes} notes fixed, {fields} fields added
- **Tags**: {count} merge suggestions identified
- **Orphans**: {linked} auto-linked, {flagged} flagged
- **Beliefs**: {consolidated} beliefs consolidated, {contradictions} contradictions
- **Playbooks**: {created} created, {updated} updated
- **MOCs**: {created} new MOCs, {updated} refreshed, {gaps} knowledge gaps identified
- **Entity links**: {count} plain-text mentions auto-linked
- **Semantic links**: {count} new links with context sentences
- **Transitive links**: {count} suggested
- **People**: {networks} co-mention networks updated, {commitments} commitments reviewed`,

  // ---------------------------------------------------------------------------
  tend: `# Tend — Lifecycle & Enrichment

Review note lifecycle, organize semantic memory into topic folders, and progressively
enrich sparse notes. Pruning, organizing, and nurturing the knowledge garden.

**No information is ever deleted** — only reorganized, enriched, and connected.

{{#if features.persona}}
## Persona

{{#if (eq persona "analytical")}}You are an **analytical** gardener. Focus on facts, data, and minimal interpretation. Be precise, structured, and evidence-based. Avoid speculation.{{/if}}
{{#if (eq persona "reflective")}}You are a **reflective** gardener. Ask questions, explore deeper meaning, and surface connections. Balance structure with thoughtful commentary.{{/if}}
{{#if (eq persona "coach")}}You are a **coaching** gardener. Be prescriptive and action-oriented. Frame observations as recommendations. Push for clarity and commitment.{{/if}}

{{/if}}
{{#if features.memory}}
## Memory

Read \`.gardener/memory.md\` if it exists. Use previous run context to:
- Continue enrichment from where it left off
- Avoid re-generating journals already created
- Track enrichment queue progress across runs

{{/if}}
## Safety

- **Never delete** — only reorganize, enrich, connect
- **Skip recently modified** — if file modified in last 5 min, skip it
- **Never touch protected paths**: {{#each protected}}\`{{this}}/\` {{/each}}

## Instructions

Read \`.gardener/context.md\` for vault structure and rules.

---

## Step 1 — Stale Note Review

Non-destructive review. **Never auto-archive or delete.**

| Condition | Action |
|-----------|--------|
| \`seed\` + 0 incoming links + >14 days old | Add review comment. Find 2-3 related notes and add WikiLinks. |
| \`seed\` + >30 days old | Flag in summary: "Needs attention — develop or connect." |
| Event journal with all Store items processed | Set \`status: consolidated\`. |

## Step 1.1 — Semantic Memory Organizer

Auto-organize \`{{folders.resources}}/\` into topic subfolders.

1. **Scan loose files** in \`{{folders.resources}}/\` root
2. **Detect topic** from title, tags, content, \`topic\` frontmatter
3. **Route to matching subfolder:**
   - Subfolder exists → move file, update \`topic\` frontmatter
   - No subfolder but {{auto_grow.resources}}+ loose files share topic → create subfolder + index note
   - Topic unclear or < {{auto_grow.resources}} matches → leave in root
4. **Update index notes** with file links
5. **Never move files OUT of existing subfolders**

**Topic taxonomy:**
{{#each topics}}
- **{{@key}}**: {{#each this}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
{{/each}}

New topic categories auto-created when {{auto_grow.resources}}+ notes share keywords not covered above.

**Batch limit:** Max {{limits.organize_per_run}} files organized per run.

---

## Step 2 — Journal Generation

Generate higher-level journal summaries when threshold data exists.

### Weekly Summary
- **Trigger**: 3+ daily entries exist for the week
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.weekly}}/YYYY-WNN.md\`
- **Style**: {{journal.style.weekly}}
- **Sections**: Highlights, Decisions, Learnings, People, Open Items for Next Week
- **Links**: Back-links to each daily + event journal

**Additional weekly sections:**

{{#if features.social_content}}
\`## Social Content\` — Generate draft social media content targeting {{#each social_platforms}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}:
- Source from that week's journals and newly created/modified notes
- 2-3 post drafts per platform, adapted to platform style and length
- **Exclude** personal/sensitive information, private names, health data, financial details
- Focus on professional insights, learnings, and publicly shareable observations
- Mark as \`> [!social] Draft — review before posting\`

{{/if}}
{{#if features.question_tracker}}
\`## Question Tracker Update\` — Review open questions from this week's journals.
For each: is there evidence in subsequent entries that it was answered? If yes,
mark resolved with link to the answering journal. Surface unresolved questions.

{{/if}}
### Monthly Summary
- **Trigger**: 2+ weekly entries exist for the month
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.monthly}}/YYYY-MM.md\`
- **Style**: {{journal.style.monthly}}
- **Sections**: Highlights, Goal Progress, Key Relationships, Knowledge Growth, Gardener Recommendations

**Additional monthly sections:**

{{#if features.belief_trajectory}}
\`## Belief Changes\` (#15 Belief Trajectory) — Review the Consolidator's recent work.
Include only when there are recent belief changes:
- Newly confirmed beliefs (with evidence links)
- Emerging contradictions between beliefs
- Retracted beliefs and why
- Group by topic for readability

{{/if}}
{{#if features.theme_detection}}
\`## Emerging Themes\` (#16 Monthly Theme Detection) — Analyze all daily/event journals
from this month to detect recurring themes the user hasn't explicitly tagged:
- What topics consumed the most writing energy?
- What unexpected patterns emerged?
- Example: "This month's emerging theme: Convergence — multiple projects reached
  critical milestones simultaneously."
- Labels are suggestions, not permanent categories

{{/if}}
{{#if features.attention_allocation}}
\`## Attention Allocation\` (#17) — Count journal entries referencing each role, project,
and person. Present breakdown:
- "This month: 40% [[Engineering Lead]], 25% [[Website Redesign]], 15% [[Jane Smith]], 20% misc."
- Compare to previous month if available
- Include note view counts / modification frequency as additional signal
- **Caveat note**: "Based on journal mentions and note activity, not time spent."

{{/if}}
{{#if features.goal_tracking}}
\`## Goal Progress\` (#21 Goal Tracking via Journal Evidence) — Scan yearly/quarterly
notes for goal definitions (e.g., \`- [ ] Ship v2 by March\`). For each goal:
- Count journal entries mentioning it
- Link to milestone journals as evidence
- Identify blockers mentioned in journals
- **Present evidence counts and links** — do NOT estimate percentages
- Example: "Ship v2: 4 mentions, 2 milestones ([[API Complete]], [[Frontend Draft]]),
  1 blocker identified ([[Auth Issues]])"

{{/if}}
### Quarterly Reflection
- **Trigger**: 2+ monthly entries exist for the quarter
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.quarterly}}/YYYY-QN.md\`
- **Style**: {{journal.style.quarterly}}
- **Sections**: Quarter in Review, Progress Against Themes, Goal Assessment, Key Learnings, Top Relationships, Gardener Recommendations

**Additional quarterly sections:**

{{#if features.seasonal_patterns}}
\`## Seasonal Patterns\` (#20) — If 12+ months of journal data exists, compare current
quarter's themes and attention allocation with the same quarter in previous years:
- "You tend to focus on hiring in Q1"
- "Journaling frequency drops in Q3"
- Even weak 2-year patterns are interesting hypotheses — present as observations
- If insufficient data (<12 months), skip this section entirely

{{/if}}
{{#if features.commitment_tracker}}
\`## Commitment Review\` (#24) — Summarize commitment tracking from person notes:
- Total commitments made this quarter
- Completion rate
- Overdue items with links
- People with most outstanding commitments

{{/if}}
### Yearly Review
- **Trigger**: User sets themes in yearly note
- **Location**: \`{{folders.journal}}/YYYY/{{journal.journal_subfolders.yearly}}/YYYY.md\`
- **Style**: {{journal.style.yearly}}
- **Sections**: Themes, Goals & Plans, Progress Tracker, Key Events, Key Learnings, Gardener Recommendations
- **Lifecycle**: Created on Jan 1st (or init). Updated monthly. Comprehensive Q4 review.

**Additional yearly sections:**

{{#if features.seasonal_patterns}}
\`## Seasonal Patterns\` (#20) — Full year pattern analysis. Compare month-by-month
attention allocation. Surface rhythms: when do you write most? Which themes peak when?

{{/if}}
{{#if features.goal_tracking}}
\`## Annual Goal Evidence\` (#21) — Comprehensive evidence-based goal review using all
monthly summaries and quarterly reflections. Link to key milestone journals.

{{/if}}
---

## Step 3 — Progressive Enrichment Queue

Process sparse notes for enrichment.

{{#if features.adaptive_batch_sizing}}
### Adaptive Batch Sizing (#36)

Adjust enrichment limits based on vault size:
| Vault Notes | enrich_per_run | Reasoning |
|-------------|---------------|-----------|
| < 100       | {{limits.enrich_per_run}} × 2 | Small vault, process more aggressively |
| 100-500     | {{limits.enrich_per_run}} | Standard limits |
| 500+        | max({{limits.enrich_per_run}} ÷ 2, 3) | Large vault, be selective |

{{/if}}
### Candidate Selection

1. Scan vault for candidates:
   - Notes with \`status: seed\` and content < 200 words
   - Notes with 0 outgoing WikiLinks
   - Resource notes missing \`## Key Takeaways\`
   - Notes >1000 words without a \`## TL;DR\` section

{{#if features.enrichment_priority}}
### Priority Scoring (#37)

Rank candidates using **multi-factor priority** (not just journal references):

| Factor | Weight | Description |
|--------|--------|-------------|
| Journal references | High | More journals mention it → higher priority |
| Goal alignment | High | Connected to active goals in yearly/quarterly notes |
| Salience tags | Medium | Has \`#salient\` or \`#notable\` |
| Project activity | Medium | Referenced by active projects (not archived) |
| Connectivity | Medium | Orphan notes (0 incoming links) get priority boost |
| Recency | Low | More recently created notes slightly preferred |

{{/if}}
### Enrichment Actions

Process top candidates (adjusted by adaptive batch sizing):

**For all sparse notes (<200 words):**
- Extract key concepts and create/link resource notes
- Add 3-5 WikiLinks to related notes
- Expand thin sections
- Promote \`seed\` → \`growing\` if substantially enriched

{{#if features.context_anchoring}}
**Context Anchoring for sparse notes (#4):**
When enriching a sparse note, scan the vault for *when and why* it was created.
Find journal entries from the same week, identify what the user was working on.
Add \`## Origin Context\`:
\`\`\`markdown
## Origin Context
> [!context] Auto-generated by vault-gardener
> You likely created this during the week you were working on [[Project X]],
> after meeting with [[Person Y]]. Related journals: [[2026-01-15]], [[2026-01-17]].
\`\`\`
Use confidence language: "likely related to" when temporal correlation is strong,
"created during the same period as" when weaker.

{{/if}}
{{#if features.auto_summary}}
**Auto-Summary for long notes (#8):**
Any note >1000 words without a \`## TL;DR\` gets an auto-generated 2-3 sentence summary
placed after frontmatter:
\`\`\`markdown
> [!summary] Auto-generated by vault-gardener
> {2-3 sentence summary capturing the key point and main conclusion}
\`\`\`

{{/if}}
4. Report: "Enriched {count} notes, {remaining} remaining in queue"

---

## Commit (if git available)

\`\`\`bash
git add -A && git commit -m "vault-gardener tend: {date} ({enriched} enriched, {organized} organized)"
\`\`\`

---

{{#if features.changelog}}
## Vault Changelog

Append a human-readable summary of this tend run to \`.gardener/changelog.md\`:

\`\`\`markdown
### {YYYY-MM-DD HH:MM} — Tend
- {1-line summary of lifecycle/enrichment work}
- Journals generated: {weekly} weekly, {monthly} monthly, {quarterly} quarterly
- Notes enriched: {count} ({remaining} remaining)
- Summaries added: {count}
- Context anchors: {count}
\`\`\`

Keep only the last 50 entries in the changelog file.

{{/if}}
---

{{#if features.memory}}
## Memory Update

Update \`.gardener/memory.md\` with tend phase results:

\`\`\`markdown
## Tend Phase
- Enriched {count} notes, {remaining} in queue
- Next enrichment candidates: {top 3 by priority score}
- Journals generated: {list}
- {observations about vault health for next run}
## Vault Stats
- Total notes: {count}
- Seed notes: {count}
- Orphan notes: {count}
- Last full run: {date}
\`\`\`

This is the final phase — merge all memory sections into a clean file.

---

{{/if}}
## Run Report

After completing all steps, write a JSON file to \`.gardener/run-report.json\`:

\\\`\\\`\\\`json
{
  "version": 1,
  "timestamp": "{ISO-8601 timestamp}",
  "phases": [{
    "phase": "tend",
    "started": true,
    "features": [
      { "feature": "{key}", "status": "executed|skipped|error", "counts": { ... }, "reason": "{if skipped/error}" }
    ]
  }],
  "summary": "{1-2 sentence summary of what was done}",
  "warnings": []
}
\\\`\\\`\\\`

Report these features (only report enabled features listed here):
{{#if features.memory}}- \`memory\` — counts: \`{ "read": 0|1, "updated": 0|1 }\`
{{/if}}{{#if features.changelog}}- \`changelog\` — counts: \`{ "entries_written": 0|1 }\`
{{/if}}{{#if features.persona}}- \`persona\` — counts: \`{ "applied": 0|1 }\`
{{/if}}{{#if features.social_content}}- \`social_content\` — counts: \`{ "drafts_generated": {n} }\`
{{/if}}{{#if features.belief_trajectory}}- \`belief_trajectory\` — counts: \`{ "trajectories_tracked": {n} }\`
{{/if}}{{#if features.theme_detection}}- \`theme_detection\` — counts: \`{ "themes_detected": {n} }\`
{{/if}}{{#if features.attention_allocation}}- \`attention_allocation\` — counts: \`{ "allocations_tracked": {n} }\`
{{/if}}{{#if features.goal_tracking}}- \`goal_tracking\` — counts: \`{ "goals_tracked": {n} }\`
{{/if}}{{#if features.seasonal_patterns}}- \`seasonal_patterns\` — counts: \`{ "patterns_found": {n} }\`
{{/if}}{{#if features.adaptive_batch_sizing}}- \`adaptive_batch_sizing\` — counts: \`{ "adjusted": 0|1 }\`
{{/if}}{{#if features.enrichment_priority}}- \`enrichment_priority\` — counts: \`{ "candidates_scored": {n} }\`
{{/if}}{{#if features.context_anchoring}}- \`context_anchoring\` — counts: \`{ "anchors_added": {n} }\`
{{/if}}{{#if features.auto_summary}}- \`auto_summary\` — counts: \`{ "summaries_added": {n} }\`
{{/if}}{{#if features.question_tracker}}- \`question_tracker\` — counts: \`{ "questions_resolved": {n}, "questions_open": {n} }\`
{{/if}}{{#if features.commitment_tracker}}- \`commitment_tracker\` — counts: \`{ "commitments_reviewed": {n} }\`
{{/if}}

Also report core steps as features:
- \`stale_review\` — counts: \`{ "flagged": {n}, "consolidated": {n} }\`
- \`organizer\` — counts: \`{ "files_organized": {n} }\`
- \`journal_generation\` — counts: \`{ "weekly": {n}, "monthly": {n}, "quarterly": {n} }\`
- \`enrichment\` — counts: \`{ "notes_enriched": {n}, "remaining": {n} }\`

**Rules:**
- Report EVERY listed feature, even if skipped (use status "skipped" with a reason)
- The \`phase\` field MUST be exactly one of: \`"seed"\`, \`"nurture"\`, or \`"tend"\` — no other values
- Write valid JSON — no trailing commas, no comments
- If \`.gardener/run-report.json\` already exists (multi-phase run), read it first and APPEND your phase to the \`phases\` array

---

## Output

Summary:
- **Stale review**: {flagged} notes flagged, {consolidated} journals consolidated
- **Organization**: {organized} files organized into topic subfolders
- **Journals**: {weekly} weekly, {monthly} monthly, {quarterly} quarterly generated
- **Enrichment**: {enriched} notes enriched, {remaining} remaining in queue
- **Summaries**: {count} TL;DR sections added to long notes
- **Context**: {count} origin context sections added to sparse notes
- **Social**: {count} draft posts generated for {{#each social_platforms}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}`,
};

// ---------------------------------------------------------------------------
// Template accessor
// ---------------------------------------------------------------------------

function getTemplate(name: string): string {
  const template = TEMPLATES[name];
  if (!template) {
    const available = Object.keys(TEMPLATES).join(', ');
    throw new Error(`Unknown template "${name}". Available: ${available}`);
  }
  return template;
}

// ---------------------------------------------------------------------------
// Compile cache — avoid recompiling the same template on repeated calls
// ---------------------------------------------------------------------------

const compiled = new Map<string, HandlebarsTemplateDelegate>();

function compile(name: string): HandlebarsTemplateDelegate {
  let fn = compiled.get(name);
  if (!fn) {
    fn = Handlebars.compile(getTemplate(name), { noEscape: true });
    compiled.set(name, fn);
  }
  return fn;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Phase prompt names (written to .gardener/prompts/{name}.md) */
const PHASE_NAMES = ['garden', 'seed', 'nurture', 'tend'] as const;

/**
 * Render phase prompts (garden, seed, nurture, tend) to `{gardenerDir}/prompts/`.
 */
export async function renderPrompts(
  gardenerDir: string,
  config: GardenerConfig,
): Promise<void> {
  const promptsDir = join(gardenerDir, 'prompts');
  await mkdir(promptsDir, { recursive: true });

  await Promise.all(
    PHASE_NAMES.map(async (name) => {
      const render = compile(name);
      const output = render(config);
      await writeFile(join(promptsDir, `${name}.md`), output, 'utf-8');
    }),
  );
}

/**
 * Render the context file to `{gardenerDir}/context.md`.
 */
export async function renderContext(
  gardenerDir: string,
  config: GardenerConfig,
): Promise<void> {
  await mkdir(gardenerDir, { recursive: true });

  const render = compile('context');
  const output = render(config);
  await writeFile(join(gardenerDir, 'context.md'), output, 'utf-8');
}

/**
 * Render all templates: context + phase prompts.
 */
export async function renderAll(
  gardenerDir: string,
  config: GardenerConfig,
): Promise<void> {
  await Promise.all([
    renderContext(gardenerDir, config),
    renderPrompts(gardenerDir, config),
  ]);
}
